server:
  port: 8085
  
spring:
  datasource:
    url: jdbc:/mysql://localhost:3306/Eureka
    password: Admin
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
  application:
    name: Eureka-server